sudo: false
cache: pip
language: python
# For pypy versions, see https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build
python:
  - 3.6
  - 3.5
  - 3.4

install:
# coveralls
  - pip install --upgrade tox-travis
  - pip install --upgrade coveralls

script:
  - tox

# after_success:
#   - coveralls --rcfile=tools/coverage_unit_tests.rc


